# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/decimal
    REF v6.0.1
    SHA512 dd7f28dcb4813f1c2dd8add8738a630dc3e1d132a4384acaaba60406825b135755f60c931240318680e7ea49707fdf3166ceb5f645a82e9ffe67d61e3d1096fb
    HEAD_REF master
    PATCHES
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)