version: '3.8'

services:
  coinbase-app:
    build: .
    container_name: coinbase-data-retriever
    env_file:
      - .env
    environment:
      - POSTGRES_USER_FILE=/app/db/postgres-u.txt
      - POSTGRES_PASSWORD_FILE=/app/db/postgres-p.txt
      - POSTGRES_HOST=cohida-db
      - POSTGRES_PORT=5432
    volumes:
      - ./db:/app/db:ro
      - ./outputs:/app/outputs
      - ./.env:/app/.env:ro
      - ./src:/app/src
    networks:
      - cohida-net

networks:
  cohida-net:
    external: true
    name: cohida-net
